// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsWd0R_XWvTWVXCcHz7J6yTaanm1t7iOg',
    appId: '1:135616622535:web:1e01c04d6d1480cb58f3e2',
    messagingSenderId: '135616622535',
    projectId: 'login-39650',
    authDomain: 'login-39650.firebaseapp.com',
    storageBucket: 'login-39650.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgBHa5aBhIhE-YRmw1XOh3tW-sGnHBaA',
    appId: '1:135616622535:android:461b8551637d308158f3e2',
    messagingSenderId: '135616622535',
    projectId: 'login-39650',
    storageBucket: 'login-39650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAffJAKEBI2o2yGWbc3VqMesUQPQMc4SBY',
    appId: '1:135616622535:ios:e00c85b5ac82749058f3e2',
    messagingSenderId: '135616622535',
    projectId: 'login-39650',
    storageBucket: 'login-39650.appspot.com',
    iosClientId: '135616622535-63920k3eehjo7es44ou26vkpigtm90ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAffJAKEBI2o2yGWbc3VqMesUQPQMc4SBY',
    appId: '1:135616622535:ios:e00c85b5ac82749058f3e2',
    messagingSenderId: '135616622535',
    projectId: 'login-39650',
    storageBucket: 'login-39650.appspot.com',
    iosClientId: '135616622535-63920k3eehjo7es44ou26vkpigtm90ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
